version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: file-upload-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mehdi
      POSTGRES_PASSWORD: secret123
      POSTGRES_DB: file_upload_db
    command: ["postgres", "-c", "password_encryption=md5"]
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-net

networks:
  backend-net:

volumes:
  postgres_data: